//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoLine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoLine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a game for software engineer coure design which develop using c#..
        /// </summary>
        public static string AboutApp {
            get {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Game Mode.
        /// </summary>
        public static string AboutGameMode {
            get {
                return ResourceManager.GetString("AboutGameMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI-AI : For test.
        ///Human-AI : AI Challenge, will record score.
        ///Free Mode : Allow local player vs local player, but the it won&apos;t record in player&apos;s score.
        ///Online : Online players  Challenge, will record score..
        /// </summary>
        public static string AboutGameModeExplain {
            get {
                return ResourceManager.GetString("AboutGameModeExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project is open source but only for learnning..
        /// </summary>
        public static string AboutOpenSource {
            get {
                return ResourceManager.GetString("AboutOpenSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT POINTS.
        /// </summary>
        public static string AboutPoints {
            get {
                return ResourceManager.GetString("AboutPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comming soon..
        /// </summary>
        public static string AboutPointsExplain {
            get {
                return ResourceManager.GetString("AboutPointsExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Score(On  built).
        /// </summary>
        public static string AboutScore {
            get {
                return ResourceManager.GetString("AboutScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win : Get one point
        ///Fail : Lost one point
        ///Drawn : Null.
        /// </summary>
        public static string AboutScoreExplain {
            get {
                return ResourceManager.GetString("AboutScoreExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced AI.
        /// </summary>
        public static string AdvancedAI {
            get {
                return ResourceManager.GetString("AdvancedAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Player.
        /// </summary>
        public static string AIPlayer {
            get {
                return ResourceManager.GetString("AIPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Player2.
        /// </summary>
        public static string AIPlayer2 {
            get {
                return ResourceManager.GetString("AIPlayer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIVSAI.
        /// </summary>
        public static string AIVSAI {
            get {
                return ResourceManager.GetString("AIVSAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always allow pay.
        /// </summary>
        public static string AlwaysAllowPay {
            get {
                return ResourceManager.GetString("AlwaysAllowPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoLine.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require .Net framework 4.5.2 for running.
        /// </summary>
        public static string AppRequire {
            get {
                return ResourceManager.GetString("AppRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto notice newest.
        /// </summary>
        public static string AutoNoticeNewest {
            get {
                return ResourceManager.GetString("AutoNoticeNewest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board line color.
        /// </summary>
        public static string BoardLineColor {
            get {
                return ResourceManager.GetString("BoardLineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        public static string ChangeLang {
            get {
                return ResourceManager.GetString("ChangeLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It needs to restart application to take effect of language setting.Restart right now?.
        /// </summary>
        public static string ChangeLangTips {
            get {
                return ResourceManager.GetString("ChangeLangTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chess Brush.
        /// </summary>
        public static string ChessBrush {
            get {
                return ResourceManager.GetString("ChessBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to refresh.
        /// </summary>
        public static string ClickToRefresh {
            get {
                return ResourceManager.GetString("ClickToRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to network.
        /// </summary>
        public static string ConnectFail {
            get {
                return ResourceManager.GetString("ConnectFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now in debug mode, app won&apos;t auto restart because of debug mode is not use the same config/setting file for app in visual studio,it needs to restart project by yourselft..
        /// </summary>
        public static string DebugExplain {
            get {
                return ResourceManager.GetString("DebugExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug mode.
        /// </summary>
        public static string DebugMode {
            get {
                return ResourceManager.GetString("DebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawn.
        /// </summary>
        public static string Drawn {
            get {
                return ResourceManager.GetString("Drawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elementary AI.
        /// </summary>
        public static string ElementaryAI {
            get {
                return ResourceManager.GetString("ElementaryAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty userName/password!.
        /// </summary>
        public static string EmptyUserNameOrPsw {
            get {
                return ResourceManager.GetString("EmptyUserNameOrPsw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        public static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front.
        /// </summary>
        public static string Front {
            get {
                return ResourceManager.GetString("Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAME ENDED.
        /// </summary>
        public static string GameEnded {
            get {
                return ResourceManager.GetString("GameEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If there is a new winner append, game ended, or if there is no winner when each of players reach the max steps, game will end..
        /// </summary>
        public static string GameEndedExplain {
            get {
                return ResourceManager.GetString("GameEndedExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate record fail.
        /// </summary>
        public static string GenerateRecordFail {
            get {
                return ResourceManager.GetString("GenerateRecordFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string Guest {
            get {
                return ResourceManager.GetString("Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest2.
        /// </summary>
        public static string Guest2 {
            get {
                return ResourceManager.GetString("Guest2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImHost.
        /// </summary>
        public static string ImHost {
            get {
                return ResourceManager.GetString("ImHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate AI.
        /// </summary>
        public static string IntermediateAI {
            get {
                return ResourceManager.GetString("IntermediateAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP.
        /// </summary>
        public static string IP {
            get {
                return ResourceManager.GetString("IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local port.
        /// </summary>
        public static string LocalPort {
            get {
                return ResourceManager.GetString("LocalPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string LogAccount {
            get {
                return ResourceManager.GetString("LogAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not login that will case your history store in guest account.Login now?.
        /// </summary>
        public static string LoginRequestTips {
            get {
                return ResourceManager.GetString("LoginRequestTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me.
        /// </summary>
        public static string Me {
            get {
                return ResourceManager.GetString("Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyTime.
        /// </summary>
        public static string ModifyTime {
            get {
                return ResourceManager.GetString("ModifyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        public static string Music {
            get {
                return ResourceManager.GetString("Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newest.
        /// </summary>
        public static string Newest {
            get {
                return ResourceManager.GetString("Newest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nick name.
        /// </summary>
        public static string NickName {
            get {
                return ResourceManager.GetString("NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other error.
        /// </summary>
        public static string OtherError {
            get {
                return ResourceManager.GetString("OtherError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Setting.
        /// </summary>
        public static string OtherSetting {
            get {
                return ResourceManager.GetString("OtherSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not the same!.
        /// </summary>
        public static string PasswordNotSame {
            get {
                return ResourceManager.GetString("PasswordNotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay code.
        /// </summary>
        public static string PayCode {
            get {
                return ResourceManager.GetString("PayCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay for it.
        /// </summary>
        public static string PayForIt {
            get {
                return ResourceManager.GetString("PayForIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLACE A CHESS.
        /// </summary>
        public static string PlaceAChess {
            get {
                return ResourceManager.GetString("PlaceAChess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just need to put you chess on the intersection of lines.Taking turns the players place this pieces on the board.
        /// </summary>
        public static string PlaceAChessExplain {
            get {
                return ResourceManager.GetString("PlaceAChessExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Player.
        /// </summary>
        public static string PrimaryPlayer {
            get {
                return ResourceManager.GetString("PrimaryPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password can&apos;t be empty!.
        /// </summary>
        public static string PSWEmptyTips {
            get {
                return ResourceManager.GetString("PSWEmptyTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human-AI.
        /// </summary>
        public static string PVE {
            get {
                return ResourceManager.GetString("PVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Mode.
        /// </summary>
        public static string PVP {
            get {
                return ResourceManager.GetString("PVP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        public static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require Login.
        /// </summary>
        public static string RequireLogin {
            get {
                return ResourceManager.GetString("RequireLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Player.
        /// </summary>
        public static string SecondaryPlayer {
            get {
                return ResourceManager.GetString("SecondaryPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Level.
        /// </summary>
        public static string SelectLevel {
            get {
                return ResourceManager.GetString("SelectLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Mode.
        /// </summary>
        public static string SelectMode {
            get {
                return ResourceManager.GetString("SelectMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select start player.
        /// </summary>
        public static string SelectStart {
            get {
                return ResourceManager.GetString("SelectStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set connection.
        /// </summary>
        public static string SetConnection {
            get {
                return ResourceManager.GetString("SetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds.
        /// </summary>
        public static string Sounds {
            get {
                return ResourceManager.GetString("Sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds effects.
        /// </summary>
        public static string SoundsEffects {
            get {
                return ResourceManager.GetString("SoundsEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPECIALS.
        /// </summary>
        public static string Specials {
            get {
                return ResourceManager.GetString("Specials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start new game.
        /// </summary>
        public static string StartNewGame {
            get {
                return ResourceManager.GetString("StartNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s in testing!.
        /// </summary>
        public static string TestingTips {
            get {
                return ResourceManager.GetString("TestingTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game ended in a tie.
        /// </summary>
        public static string TieEnded {
            get {
                return ResourceManager.GetString("TieEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips.
        /// </summary>
        public static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total times.
        /// </summary>
        public static string TotalTimes {
            get {
                return ResourceManager.GetString("TotalTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateTime {
            get {
                return ResourceManager.GetString("UpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account exists!.
        /// </summary>
        public static string UserExist {
            get {
                return ResourceManager.GetString("UserExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName can&apos;t be empty!.
        /// </summary>
        public static string UserNameEmptyTips {
            get {
                return ResourceManager.GetString("UserNameEmptyTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not exist!.
        /// </summary>
        public static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Github.
        /// </summary>
        public static string VisitGithub {
            get {
                return ResourceManager.GetString("VisitGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win.
        /// </summary>
        public static string Win {
            get {
                return ResourceManager.GetString("Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIN THE GAME.
        /// </summary>
        public static string WinTheGame {
            get {
                return ResourceManager.GetString("WinTheGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A player win only when first complete place three chess in one line.
        /// </summary>
        public static string WinTheGameExplain {
            get {
                return ResourceManager.GetString("WinTheGameExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password.
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
    }
}
